rulelist = 1*rule
rule = rulename *wsp "=" *wsp alternation *wsp c-nl
rulename = ALPHA *namechar
namechar = ALPHA / DIGIT / "-"
alternation = concatenation *altrest
altrest = *wsp "/" *wsp concatenation
concatenation = repetition *catrest
catrest = 1*wsp repetition
repetition = repeat-opt element
repeat-opt = *1repeat
repeat = repeat-exact / repeat-range
repeat-exact = decits
repeat-range = lo-bound "*" hi-bound
lo-bound = *1decits
hi-bound = *1decits
decits = 1*DIGIT
element = rulename / char-val / num-val / group
group = "(" *wsp alternation *wsp ")"
char-val = DQUOTE *vchar-nq DQUOTE
vchar-nq = %x20-21 / %x23-7E
num-val = num-single / num-range
num-single = "%" "x" hexits
num-range = "%" "x" hexits "-" hexits
hexits = 1*HEXDIG
c-nl = *1CR LF
wsp = SP / HTAB
ALPHA = %x41-5A / %x61-7A
DIGIT = %x30-39
HEXDIG = DIGIT / "A" / "B" / "C" / "D" / "E" / "F"
CR = %x0D
LF = %x0A
SP = %x20
HTAB = %x09
DQUOTE = %x22
