# GENERATED by builder.py from json_ws.gbnf — DO NOT EDIT
# Run: uv run builder.py json_ws.gbnf
from __future__ import annotations
from typing import Any, Optional, Union
from pydantic import BaseModel, Field


class Start(BaseModel):
    root: Object


class Value(BaseModel):
    root: Union[Object, Array, str, tuple[str, str]]


class Object(BaseModel):
    ws: str
    strings: Optional[tuple[str, str, Value, list[tuple[str, str, str, Value]]]] = None
    ws_1: str


class Array(BaseModel):
    ws: str
    values: Optional[tuple[Value, list[tuple[str, Value]]]] = None
    ws_1: str


# Resolve forward references
Start.model_rebuild()
Value.model_rebuild()
Object.model_rebuild()
Array.model_rebuild()
