# GENERATED by builder.py from json_ws.gbnf — DO NOT EDIT
# Run: uv run builder.py json_ws.gbnf
from __future__ import annotations
import re
from typing import Optional
from .models import Start, Value, Object, Array


class ParseError(Exception):
    def __init__(self, rule: str, pos: int, text: str):
        ctx = text[max(0, pos - 20) : pos + 20]
        super().__init__(f"Parse error in {rule!r} at pos {pos}: ...{ctx!r}...")


def _re_match(pattern: str, text: str, pos: int) -> Optional[tuple[str, int]]:
    m = re.match(pattern, text[pos:], re.DOTALL)
    if m:
        return m.group(0), pos + len(m.group(0))
    return None


def parse(text: str, start: str = "packet") -> object:
    """Parse Vyx text. start must be a non-terminal rule name (snake_case)."""
    fn = globals().get(f"parse_{start}")
    if fn is None:
        raise ValueError(f"Unknown start rule: {start!r}")
    result, pos = fn(text, 0)
    while pos < len(text) and text[pos] in " \t\n\r":
        pos += 1
    if pos != len(text):
        raise ParseError(start, pos, text)
    return result


# --- Terminal parsers ---

def _parse_STRING(text: str, pos: int) -> tuple[str, int]:
    m = _re_match('"(?:(?:\\\\(?:u[0-9a-fA-F]{4,4}|["\\\\bfnrt])|[^"\\\\\\x7F\\x00-\\x1F]))*"(?:\\\n[ \\t]{0,20}|\\ |)', text, pos)
    if m is None:
        raise ParseError('STRING', pos, text)
    return m

def _parse_NUMBER(text: str, pos: int) -> tuple[str, int]:
    m = _re_match('(?:\\-)?(?:[1-9][0-9]{0,15}|[0-9])(?:\\.[0-9]+)?[eE][-+]?[0-9][1-9]{0,15}?(?:\\\n[ \\t]{0,20}|\\ |)', text, pos)
    if m is None:
        raise ParseError('NUMBER', pos, text)
    return m

def _parse_WS(text: str, pos: int) -> tuple[str, int]:
    m = _re_match('(?:\\\n[ \\t]{0,20}|\\ |)', text, pos)
    if m is None:
        raise ParseError('WS', pos, text)
    return m

# --- Non-terminal parsers ---

def parse_start(text: str, pos: int) -> tuple[Start, int]:
    inner, pos = parse_object(text, pos)
    return Start(root=inner), pos

def parse_value(text: str, pos: int) -> tuple[Value, int]:
    _start = pos
    try:
        inner, pos = parse_object(text, pos)
        return Value(root=inner), pos
    except ParseError:
        pos = _start
    try:
        inner, pos = parse_array(text, pos)
        return Value(root=inner), pos
    except ParseError:
        pos = _start
    try:
        val, pos = _parse_STRING(text, pos)
        return Value(root=val), pos
    except ParseError:
        pos = _start
    try:
        val, pos = _parse_NUMBER(text, pos)
        return Value(root=val), pos
    except ParseError:
        pos = _start
    try:
        pass
    except ParseError:
        pos = _start
    raise ParseError('value', pos, text)

def parse_object(text: str, pos: int) -> tuple[Object, int]:
    strings = None
    if not text[pos:].startswith('{'):
        raise ParseError('object', pos, text)
    pos += 1
    ws, pos = _parse_WS(text, pos)
    _opt_pos = pos
    try:
        string, pos = _parse_STRING(text, pos)
        if not text[pos:].startswith(':'):
            raise ParseError('object', pos, text)
        pos += 1
        ws, pos = _parse_WS(text, pos)
        value, pos = parse_value(text, pos)
    except ParseError: pos = _opt_pos
    if not text[pos:].startswith('}'):
        raise ParseError('object', pos, text)
    pos += 1
    ws_1, pos = _parse_WS(text, pos)
    return Object(ws=ws, ws_1=ws_1), pos

def parse_array(text: str, pos: int) -> tuple[Array, int]:
    values = None
    if not text[pos:].startswith('['):
        raise ParseError('array', pos, text)
    pos += 1
    ws, pos = _parse_WS(text, pos)
    _opt_pos = pos
    try:
        value, pos = parse_value(text, pos)
    except ParseError: pos = _opt_pos
    if not text[pos:].startswith(']'):
        raise ParseError('array', pos, text)
    pos += 1
    ws_1, pos = _parse_WS(text, pos)
    return Array(ws=ws, ws_1=ws_1), pos

