"""Shipped-manifest conformance — the settled-9 comparator (MANIFEST_DESIGN §10).

The GBNF and ABNF ``*.flavour.ir`` manifests (``src/lexic/grammars/``, read via
filesystem path — no package-data import needed) load to flavours conformant
with their authored singletons under all seven comparator steps:

1. identity fields (name / extensions / line-comment);
2. per-section canonical-repr equality (grammar / reductions / actions);
3. explicit ``non_semantic`` set equality (C11 — ``IrRule.__eq__`` ignores
   ``semantic``);
4. escape codec BEHAVIOURAL parity (synthesized codec classes never ``==``);
5. equal ``parse_grammar`` across the flavour's ground-truth corpus;
6. equal emitted text on the corpus's canonical IR;
7. the integration run — register under the authored name, compile a GT
   grammar, parse an instance, exact ``to_text`` round-trip — behind the
   registry snapshot/restore + cache-reset fixture.

The manifests are regenerated by ``tools/gen_manifests.py``; these gates fail by
design when an authored singleton drifts from its committed manifest.
"""

from __future__ import annotations

import pytest

import lexic.compile as compile_pkg
from lexic.compile import parse_grammar
from lexic.compile.notation.loader import load_flavour_from_path
from lexic.grammars import ABNF_FLAVOUR, GBNF_FLAVOUR, register_flavour
from lexic.grammars.abnf import (
    ABNF_ACTIONS,
    ABNF_ESCAPES,
    ABNF_GRAMMAR,
    ABNF_REDUCTIONS,
)
from lexic.grammars.gbnf import (
    GBNF_ACTIONS,
    GBNF_ESCAPES,
    GBNF_GRAMMAR,
    GBNF_REDUCTIONS,
)
from lexic.ir.canonical import canonicalize
from lexic.ir.escapes import EscapeCodec
from lexic.ir.flavour import IrFlavour
from lexic.parsing import Reducer
from tests.paths import ABNF_GRAMMARS, GBNF_GRAMMARS, GRAMMARS, GROUND_TRUTH

GBNF_CORPUS = GBNF_GRAMMARS
ABNF_CORPUS = ABNF_GRAMMARS


def load(stem: str) -> IrFlavour:
    """Load a shipped manifest by stem (e.g. ``gbnf``)."""
    return load_flavour_from_path(GRAMMARS / f"{stem}.flavour.ir")


def reducer(flavour: IrFlavour) -> Reducer:
    """The flavour's reducer, narrowed to :class:`Reducer` for its policy attrs."""
    result = flavour.reducer
    assert isinstance(result, Reducer)
    return result


# The ``registry_snapshot`` fixture is shared from ``tests/conftest.py``.


# ── steps 1–4 (identity / repr / non_semantic / codec behaviour) ──────────


def test_gbnf_identity_repr_and_non_semantic() -> None:
    """GBNF steps 1–3: identity fields, per-section repr, non_semantic (C11)."""
    loaded = load("gbnf")
    assert loaded.name == "gbnf"
    assert loaded.extensions == (".gbnf",)
    assert loaded.line_comment == "#"
    assert repr(loaded.grammar) == repr(GBNF_GRAMMAR)
    assert repr(reducer(loaded).actions) == repr(GBNF_REDUCTIONS)
    assert repr(loaded.actions) == repr(GBNF_ACTIONS)
    assert loaded.grammar.non_semantic == GBNF_GRAMMAR.non_semantic


def test_abnf_identity_repr_and_non_semantic() -> None:
    """ABNF steps 1–3."""
    loaded = load("abnf")
    assert loaded.name == "abnf"
    assert loaded.extensions == (".abnf",)
    assert loaded.line_comment == ";"
    assert repr(loaded.grammar) == repr(ABNF_GRAMMAR)
    assert repr(reducer(loaded).actions) == repr(ABNF_REDUCTIONS)
    assert repr(loaded.actions) == repr(ABNF_ACTIONS)
    assert loaded.grammar.non_semantic == ABNF_GRAMMAR.non_semantic


def assert_codec_parity(
    loaded: EscapeCodec, authored: EscapeCodec, points: tuple[int, ...]
) -> None:
    """Step 4 — behavioural codec parity on a pinned battery."""
    assert isinstance(loaded, EscapeCodec) and isinstance(authored, EscapeCodec)
    assert loaded.encode("\n\t\\") == authored.encode("\n\t\\")
    for cp in points:  # spellable code points for this codec's tables
        assert loaded.encode_point(cp) == authored.encode_point(cp)
    assert loaded.spellable("abc") == authored.spellable("abc")
    assert loaded.spellable('a"b') == authored.spellable('a"b')


def test_gbnf_escape_codec_behavioural_parity() -> None:
    """GBNF step 4 — control (CLASS_SHORT), ``]`` (CLASS_META), printables."""
    assert_codec_parity(
        load("gbnf").escapes, GBNF_ESCAPES, (0x0A, 0x09, 0x5D, ord("A"), ord("-"))
    )


def test_abnf_escape_codec_behavioural_parity() -> None:
    """ABNF step 4 — the identity codec spells only printables."""
    assert_codec_parity(
        load("abnf").escapes, ABNF_ESCAPES, (ord("A"), ord("-"), ord(" "))
    )


# ── step 5 (parse parity across the corpus) ───────────────────────────────


@pytest.mark.parametrize("grammar_file", GBNF_CORPUS)
def test_gbnf_parse_parity(grammar_file: str) -> None:
    """GBNF step 5 — loaded vs authored ``parse_grammar`` on every GT grammar."""
    text = (GROUND_TRUTH / grammar_file).read_text(encoding="utf-8")
    assert parse_grammar(text, load("gbnf")) == parse_grammar(text, GBNF_FLAVOUR)


@pytest.mark.parametrize("grammar_file", ABNF_CORPUS)
def test_abnf_parse_parity(grammar_file: str) -> None:
    """ABNF step 5."""
    text = (GROUND_TRUTH / grammar_file).read_text(encoding="utf-8")
    assert parse_grammar(text, load("abnf")) == parse_grammar(text, ABNF_FLAVOUR)


# ── step 6 (emit parity on the corpus's canonical IR) ─────────────────────


@pytest.mark.parametrize("grammar_file", GBNF_CORPUS)
def test_gbnf_emit_parity(grammar_file: str) -> None:
    """GBNF step 6 — loaded vs authored emit on the grammar's canonical IR."""
    text = (GROUND_TRUTH / grammar_file).read_text(encoding="utf-8")
    canonical = canonicalize(parse_grammar(text, GBNF_FLAVOUR))
    assert load("gbnf").apply(canonical) == GBNF_FLAVOUR.apply(canonical)


@pytest.mark.parametrize("grammar_file", ABNF_CORPUS)
def test_abnf_emit_parity(grammar_file: str) -> None:
    """ABNF step 6."""
    text = (GROUND_TRUTH / grammar_file).read_text(encoding="utf-8")
    canonical = canonicalize(parse_grammar(text, ABNF_FLAVOUR))
    assert load("abnf").apply(canonical) == ABNF_FLAVOUR.apply(canonical)


# ── step 7 (integration under the authored name) ──────────────────────────


@pytest.mark.usefixtures("registry_snapshot")
def test_gbnf_manifest_drives_the_compile_pipeline() -> None:
    """GBNF step 7 — register → compile → parse → exact ``to_text`` round-trip."""
    register_flavour(load("gbnf"))
    text = (GROUND_TRUTH / "json.gbnf").read_text(encoding="utf-8")
    cg = compile_pkg.compile_text(text, flavour="gbnf")
    sample = '{"a": [1, true, "x"]}'
    assert cg.parse(sample).to_text() == sample


@pytest.mark.usefixtures("registry_snapshot")
def test_abnf_manifest_drives_the_compile_pipeline() -> None:
    """ABNF step 7."""
    register_flavour(load("abnf"))
    text = (GROUND_TRUTH / "arithmetic.abnf").read_text(encoding="utf-8")
    cg = compile_pkg.compile_text(text, flavour="abnf")
    sample = "1+2*3"
    assert cg.parse(sample).to_text() == sample
