"""The README's numbers are rendered, never typed — and never stale.

Every figure inside the README's ``lexic:begin``/``lexic:end`` markers and
every chart under ``docs/assets/`` is generated by ``tools.render_readme``
from the committed benchmark artifacts. This gate re-renders and compares, so
a baseline change without a README re-render fails the suite instead of
shipping stale numbers.
"""

import re
from pathlib import Path

from tools.render_readme import README, rendered_blocks, stale

ROOT = Path(__file__).resolve().parents[4]


def test_readme_render_is_current() -> None:
    """A fresh render of every block and asset matches what is checked in."""
    assert stale() == [], "run `uv run python -m tools.render_readme`"


def test_readme_carries_every_owned_marker() -> None:
    """Each rendered block has exactly one begin/end marker pair."""
    text = README.read_text(encoding="utf-8")
    for name in rendered_blocks():
        assert text.count(f"<!-- lexic:begin {name} -->") == 1, name
        assert text.count(f"<!-- lexic:end {name} -->") == 1, name


def test_readme_image_references_exist() -> None:
    """Every image path the README embeds is a committed file."""
    text = README.read_text(encoding="utf-8")
    paths = re.findall(r"!\[[^\]]*\]\(([^)]+\.svg)\)", text)
    assert paths, "the README embeds its charts as markdown images"
    missing = [p for p in paths if not (ROOT / p).is_file()]
    assert missing == [], missing
