# GENERATED by builder.py from vyx.gbnf — DO NOT EDIT
# Run: uv run builder.py vyx.gbnf
from __future__ import annotations
from typing import Any, Optional, Union
from pydantic import BaseModel, Field


class Start(BaseModel):
    root: Union[Packet, BodyContent]


class SeqItem(BaseModel):
    seq_indent: str
    ref_ids: Optional[str] = None
    item_head: Optional[str] = None
    item_childs: list[ItemChild] = Field(default_factory=list)


class ItemChild(BaseModel):
    child_indent: str
    body_line: BodyLine


class AnnChild(BaseModel):
    ann_indent: str
    ann_indent_1: str
    body_line: BodyLine


class RowAnnotation(BaseModel):
    ann_indent: str
    row_key: str
    scope_path: str
    kv_pairs_list: Optional[str] = None
    ann_childs: list[AnnChild] = Field(default_factory=list)


class TableBlock(BaseModel):
    table_header: str
    table_rows: list[str] = Field(default_factory=list)
    row_annotations: list[RowAnnotation] = Field(default_factory=list)


class BodyLine(BaseModel):
    root: Union[str, TableBlock, SeqItem]


class BodyContent(BaseModel):
    value: list[BodyLine]


class Body(BaseModel):
    body_content: BodyContent


class Packet(BaseModel):
    definitions: list[str] = Field(default_factory=list)
    envelope: str
    body: Optional[Body] = None


# Resolve forward references
Start.model_rebuild()
SeqItem.model_rebuild()
ItemChild.model_rebuild()
AnnChild.model_rebuild()
RowAnnotation.model_rebuild()
TableBlock.model_rebuild()
BodyLine.model_rebuild()
BodyContent.model_rebuild()
Body.model_rebuild()
Packet.model_rebuild()
